<?php

namespace REFBundle\Repository;

/**
 * RefRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RefRepository extends \Doctrine\ORM\EntityRepository
{
}
