# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    encoders:
       Symfony\Component\Security\Core\User\User: plaintext  
#       OC\PlatformBundle\Provider\User: plaintext
#       OC\PlatformBundle\Entity\User: plaintext
#    
    providers:
#        main:
#          id: main_provider
        in_memory:
            memory:
                users:
                    toto:
                        password: toto123
                        roles: ROLE_ADMIN
            

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            #http_basic: ~
            # activate different ways to authenticate
#            pattern: ^/
            #form_login: ~
            #logout:
               #path:   /logout
               #target: /
               
   # access_control:
    #    - {path: /validation, roles: ROLE_ADMIN}
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: false
       