services:
    oc_plateform_antifloodvalidator:
        class: OC\PlatformBundle\Validator\AntifloodValidator
        tags:
            - {name: validator.constraint_validator, alias: oc_platform_antiflood}